# Dependencies
markdown:         redcarpet
pygments:         false
baseurl: 	      /TeamPass
encoding: 		  UTF-8

# Permalinks
permalink:        pretty

# Setup
name: 			  Teampass
title:            Teampass
tagline:          'A Collaborative Passwords Manager'
description:      'TeamPass is a Passwords Manager dedicated for managing passwords in a collaborative way.'
#url:              http://teampass.net
url:			  http://localhost:4000

author:
  name:           'Nils Laumaillé'
  # url:          http://teampass.net

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/nilsteampassnet/TeamPass

